export {
  TextClasses,
  ColorClasses,
  ColorFG,
  ColorFGClasses,
  ColorBG,
  ColorBGClasses,
  ColorScheme,
  ColorSchemeClasses,
  type ColorSchemeState,
  type ColorSchemeManager,
  BrowserColorSchemeManager,
  type ColorSchemeCtx,
  ColorSchemeProvider,
  useColorScheme,
} from './base.js';
