routes:
  - prefix: /static/icon/
    dir: true
    path: static/icon
    cachecontrol: 'public, max-age=31536000, no-cache'
  - prefix: /static/
    dir: true
    path: static
    cachecontrol: 'public, max-age=31536000, immutable'
    compressed:
      - code: br
        test: '\.(html|js|css|json)(\.map)?$'
        suffix: .br
      - code: gzip
        test: '\.(html|js|css|json)(\.map)?$'
        suffix: .gz
  - prefix: /favicon.ico
    path: favicon.ico
    cachecontrol: 'public, max-age=31536000, no-cache'
  - prefix: /manifest.json
    path: manifest.json
    cachecontrol: 'public, max-age=31536000, no-cache'
    compressed:
      - code: br
        suffix: .br
      - code: gzip
        suffix: .gz
  - prefix: /
    path: index.html
    cachecontrol: 'public, max-age=31536000, no-cache'
    compressed:
      - code: br
        suffix: .br
      - code: gzip
        suffix: .gz
